<a href="https://colab.research.google.com/github/ruthchica31/IA-2024-2/blob/main/05_11_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Library

In [ ]:
import numpy as tmp

In [ ]:
print(tmp.__version__)


1.26.4


In [ ]:
myArr = tmp.array([1,2,3,4,5])
print(myArr)

[1 2 3 4 5]


In [ ]:
print(type(myArr))

<class 'numpy.ndarray'>


In [ ]:
print(myArr.shape)
print(myArr[2])
myArr[2] = 29
print(myArr)

(5,)
10
[ 1  2 29  4  5]


In [ ]:
myArr1=tmp.array([[1,2,3],[4,5,6]])
print(myArr1)
print(myArr1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
myArr3=tmp.zeros((5,5))
print(myArr3)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
myArr4=tmp.full((3,6),10)
print(myArr4)
myArr5=tmp.eye(5)
print(myArr5)
myArr6=tmp.random.random((3,4))
print(myArr6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.34299808 0.97878199 0.21436882 0.54735629]
 [0.20490155 0.64877764 0.19187911 0.27510043]
 [0.1163527  0.44908068 0.73600071 0.29873526]]


In [ ]:
myArr7=tmp.random.random((5,5))
print(myArr7)

[[0.99587664 0.36674343 0.86459688 0.15271238 0.73321426]
 [0.70698554 0.51793265 0.94285242 0.58066919 0.27347871]
 [0.53131576 0.72903392 0.27182263 0.14212652 0.90643171]
 [0.0637591  0.79337691 0.65480723 0.6217096  0.68678729]
 [0.72040408 0.22002142 0.5822406  0.87510018 0.85152758]]


In [ ]:
myArr8=tmp.random.randint(100,size=(5,5))
print(myArr8)

[[23 42 39  3 78]
 [24 95 62 80 36]
 [47 57  0 19 16]
 [68 28 56  5 80]
 [44 22  6 36 11]]


In [ ]:
newMatrix=myArr8[:2,:2]
print(newMatrix)

[[23 42]
 [24 95]]


In [ ]:
myArr8[2,2]=1000
print(myArr8)

[[  23   42   39    3   78]
 [  24   95   62   80   36]
 [  47   57 1000   19   16]
 [  68   28   56    5   80]
 [  44   22    6   36   11]]


In [ ]:
print(myArr8[2,:])

[  47   57 1000   19   16]


In [ ]:
print(myArr8[:,2].shape)

(5,)


In [ ]:
subMatrix=myArr8[1:4,1:4]
print(subMatrix)

[[  95   62   80]
 [  57 1000   19]
 [  28   56    5]]


In [ ]:
#
import numpy as np
matrixA=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(matrixA.shape)

(3, 4)


In [ ]:
matrixA

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [ ]:
print(matrixA[1:,1:3])

[[22 23]
 [32 33]]


In [ ]:
# Create a 4x3 matrix filled with zeros
matrixB = np.random.randint(0,10,size=(4, 3))
print(matrixB)


[[3 4 6]
 [5 5 7]
 [4 2 3]
 [9 7 9]]


In [ ]:
print(matrixB)
col_indices = np.array([0, 1, 2])
row_indices = np.array([1, 2])
for row_indices in zip(row_indices, col_indices):
        #print(row,"_",col)
        print(matrixB[row_indices])


[[3 4 6]
 [5 5 7]
 [4 2 3]
 [9 7 9]]
5
2


In [ ]:
print(matrixB)

[[3 4 6]
 [5 5 7]
 [4 2 3]
 [9 7 9]]


In [ ]:
matrixB[matrixB%2==0]+=100
print(matrixB)

[[  3 104 106]
 [  5   5   7]
 [104 102   3]
 [  9   7   9]]


In [ ]:
print(matrixB)

[[  3 104 106]
 [  5   5   7]
 [104 102   3]
 [  9   7   9]]


In [ ]:
matrixC=np.random.rand(2,2)
print(matrixC)

[[0.22896703 0.35702538]
 [0.43861468 0.27926908]]


In [ ]:
filter=(matrixB>3) & (matrixB<9)
matrixB[filter]+=100
print(matrixB)

[[  3 104 106]
 [105 105 107]
 [104 102   3]
 [  9 107   9]]


In [ ]:
matrixA1=np.random.randint(0,10, size=(2,2))
matrixA2=np.random.randint(0,10, size=(2,2))
print(matrixA1)
print(matrixA2)

[[5 3]
 [1 7]]
[[0 7]
 [6 0]]


In [ ]:
print(matrixA1+matrixA2)
print(matrixA1-matrixA2)
print(matrixA1*matrixA2)
print(matrixA1/matrixA2)


[[ 5 10]
 [ 7  7]]
[[ 5 -4]
 [-5  7]]
[[ 0 21]
 [ 6  0]]
[[       inf 0.42857143]
 [0.16666667        inf]]


<ipython-input-40-d9a4810fe26b>:4: RuntimeWarning: divide by zero encountered in divide
  print(matrixA1/matrixA2)


In [ ]:
print((matrixA1))

[[5 3]
 [1 7]]


In [ ]:
print(np.sqrt(matrixA1))

[[2.23606798 1.73205081]
 [1.         2.64575131]]


In [ ]:
matrixA1=np.random.randint(0,10, size=(2,5))
print(matrixA1)

[[4 2 5 3 0]
 [8 1 6 6 3]]


In [ ]:
print(np.mean(matrixA1))


3.8


In [ ]:
print(matrixA1.mean(axis=1))


[2.8 4.8]


In [ ]:
print(matrixA1.mean(axis=0))

[6.  1.5 5.5 4.5 1.5]


In [ ]:
print(np.std(matrixA1))

2.3579652245103193


In [ ]:
print(np.median(matrixA1))


3.5


In [ ]:
print(matrixA1.sum())

38


In [ ]:
print(matrixA1.max())

8


In [ ]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
add_rows=np.array([1,2,3])
print(add_rows.shape)

(3,)


In [ ]:
y=start+add_rows
print(y)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#col_rows=np.array([[1,2,3,4]])
print (start)
#col_rows=col_rows.T
#print(col_rows.T)
tmp=col_rows.T
#print(tmp.shape)
y2=start+tmp
print(y2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [ ]:
tmp1=np.array([[1,1],[2,2]])
tmp2=np.array([[3,3],[4,4]])
print(tmp1)
print(tmp2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [ ]:
y1=np.random.randint(low=2,high=50,size(2,2))
y2=np.random.randint(low=2,high=50,size(2,2))
print(y1)
print(y2)

SyntaxError: positional argument follows keyword argument (<ipython-input-72-5e5e1d2b963c>, line 1)

In [ ]:
np.vstact((y1,y2))

AttributeError: module 'numpy' has no attribute 'vstact'