<a href="https://colab.research.google.com/github/ruthchica31/IA-2024-2/blob/main/29_10_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Library

In [1]:
import numpy as tmp

In [2]:
print(tmp.__version__)


1.26.4


In [4]:
myArr = tmp.array([1,2,3,4,5])
print(myArr)

[1 2 3 4 5]


In [5]:
print(type(myArr))

<class 'numpy.ndarray'>


In [11]:
print(myArr.shape)
print(myArr[2])
myArr[2] = 29
print(myArr)

(5,)
10
[ 1  2 29  4  5]


In [13]:
myArr1=tmp.array([[1,2,3],[4,5,6]])
print(myArr1)
print(myArr1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [17]:
myArr3=tmp.zeros((5,5))
print(myArr3)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
myArr4=tmp.full((3,6),10)
print(myArr4)
myArr5=tmp.eye(5)
print(myArr5)
myArr6=tmp.random.random((3,4))
print(myArr6)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.34299808 0.97878199 0.21436882 0.54735629]
 [0.20490155 0.64877764 0.19187911 0.27510043]
 [0.1163527  0.44908068 0.73600071 0.29873526]]


In [21]:
myArr7=tmp.random.random((5,5))
print(myArr7)

[[0.99587664 0.36674343 0.86459688 0.15271238 0.73321426]
 [0.70698554 0.51793265 0.94285242 0.58066919 0.27347871]
 [0.53131576 0.72903392 0.27182263 0.14212652 0.90643171]
 [0.0637591  0.79337691 0.65480723 0.6217096  0.68678729]
 [0.72040408 0.22002142 0.5822406  0.87510018 0.85152758]]


In [23]:
myArr8=tmp.random.randint(100,size=(5,5))
print(myArr8)

[[23 42 39  3 78]
 [24 95 62 80 36]
 [47 57  0 19 16]
 [68 28 56  5 80]
 [44 22  6 36 11]]


In [25]:
newMatrix=myArr8[:2,:2]
print(newMatrix)

[[23 42]
 [24 95]]


In [27]:
myArr8[2,2]=1000
print(myArr8)

[[  23   42   39    3   78]
 [  24   95   62   80   36]
 [  47   57 1000   19   16]
 [  68   28   56    5   80]
 [  44   22    6   36   11]]


In [29]:
print(myArr8[2,:])

[  47   57 1000   19   16]


In [30]:
print(myArr8[:,2].shape)

(5,)


In [34]:
subMatrix=myArr8[1:4,1:4]
print(subMatrix)

[[  95   62   80]
 [  57 1000   19]
 [  28   56    5]]
